### ISSUE TITLE
Public server redundancy

### ISSUE THREAD

**Issue by jaredmoody** [KenjiOhtsuka/chainpoint_gem#5]
From the [official chainpoint js client README](https://github.com/chainpoint/chainpoint-client-js):

> By default hashes are submitted to three Nodes to help ensure a proof will become available at the appropriate time. Only one such proof need be permanently stored, the others provide redundancy.

It looks like this client only submits hashes to a single node. Do you think building this same redundancy is necessary or would be valuable?

**Comment by KenjiOhtsuka** [comment]
Hello, @jaredmoody , and thank you for creating the new issue.

When I had developed this gem, I have not read the official client library.
As you wrote, redundancy looks good, and this gem doesn't send the request to 3 nodes.

I will read the official client and consider how to implement the method in this gem.

I think the redundancy may be valuable, because chainpoint servers are run by some members in my understanding, and we can't know when each server will be closed. It might get closed abruptly.

**Comment by jaredmoody** [comment]
I am working on this and will submit a PR in the next couple days.
